---
title: "titanic"
output: html_document
date: "2022-07-29"
---
Let's explore the titanic dataset from kaggle.com!

```{r include = FALSE}
include = FALSE
library(tidyverse)
library(ggpmisc)
BASEPATH = "~/kaggle/EDA/titanic"
setwd(BASEPATH)
```

```{r }
titanic <- read.csv('data/train.csv')
```

We have `r nrow(titanic)` unique passengers, with `r ncol(titanic) -1 ` features describing them. We are most interested in their survival status, as reflected in the 'Survived' feature. While a little morbid, let's look at some graphs of who survived.
<br />

```{r echo=FALSE}
bounty <- function(lofb){
  #input: list of booleans
  #changes 1 to "Alive"
  #changes 0 to "Dead"
  lofb[lofb==1] = "Alive"
  lofb[lofb==0] = "Dead"
  return(lofb)
}
t <- as.data.frame(table(bounty(titanic$Survived)))
colnames(t) <- c("Status","Freq")

ggplot(titanic, aes(x=bounty(Survived),)) +
  geom_bar(fill=c("grey","lightblue"),colour="black")+
  xlab("Survival Status")+
  ylab("")+
  annotate(geom="table",
               x=.5,
               y=500,
               label=list(t))
```
```{r echo = False}
# Survival based on social class (colored histograms w/ the trend lines?)
# ditto 
```

